/*
 * This file is part of lanterna (https://github.com/mabe02/lanterna).
 *
 * lanterna is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright (C) 2010-2024 Martin Berglund
 */
package com.googlecode.lanterna.terminal

import com.googlecode.lanterna.*
import com.googlecode.lanterna.TextColor
import com.googlecode.lanterna.terminal.swing.SwingTerminal
import java.awt.event.ActionEvent
import java.awt.event.ActionListener
import java.util.Random
import javax.swing.*

/**
 *
 * @author martin
 */
class NewSwingTerminalTest : javax.swing.JFrame() {
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private var splitPane: javax.swing.JSplitPane? = null

/**
     * Creates new form NewSwingTerminalTest
     */
    init {
        initComponents()

        val leftTerminal = SwingTerminal()
        val rightTerminal = SwingTerminal()
        splitPane!!.setLeftComponent(leftTerminal)
        splitPane!!.setRightComponent(rightTerminal)
        pack()

        val timer =
            Timer(
                500,
                object : ActionListener {
                    override fun actionPerformed(e: ActionEvent?) {
                        drawRandomHello(leftTerminal)
                        drawRandomHello(rightTerminal)
                    }

                    private fun drawRandomHello(terminal: IOSafeTerminal) {
                        val size = terminal.terminalSize
                        if (size!!.columns > 6 && size!!.rows > 1) {
                            val positionX = RANDOM.nextInt(size!!.columns - 6)
                            val positionY = RANDOM.nextInt(size!!.rows)

                            terminal.setCursorPosition(positionX, positionY)
                            terminal.setBackgroundColor(TextColor.Indexed(RANDOM.nextInt(256)))
                            terminal.setForegroundColor(TextColor.Indexed(RANDOM.nextInt(256)))
                            val hello = "Hello!"
                            for (i in 0 until hello.length) {
                                terminal.putCharacter(hello[i])
                            }
                            terminal.flush()
                        }
                    }
                },
            )
        timer.start()
    }

    /*
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private fun initComponents() {
        splitPane = javax.swing.JSplitPane()

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE)

        splitPane!!.setDividerLocation(250)
        getContentPane().add(splitPane, java.awt.BorderLayout.CENTER)

        pack()
    } // </editor-fold>//GEN-END:initComponents

    companion object {
        private val serialVersionUID = 1L
        private val RANDOM = Random()

        /*
         * @param args the command line arguments
         */
        fun main(args: Array<String?>?) {
            // Set the Nimbus look and feel
            // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

            /*
             * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
             */
            try {
                for (info in javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info!!.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info!!.getClassName())
                        break
                    }
                }
            } catch (ex: ClassNotFoundException) {
                java.util.logging.Logger.getLogger(NewSwingTerminalTest::class.java!!.getName()).log(java.util.logging.Level.SEVERE, null, ex)
            } catch (ex: InstantiationException) {
                java.util.logging.Logger.getLogger(NewSwingTerminalTest::class.java!!.getName()).log(java.util.logging.Level.SEVERE, null, ex)
            } catch (ex: UnsupportedLookAndFeelException) {
                java.util.logging.Logger.getLogger(NewSwingTerminalTest::class.java!!.getName()).log(java.util.logging.Level.SEVERE, null, ex)
            } catch (ex: IllegalAccessException) {
                java.util.logging.Logger.getLogger(NewSwingTerminalTest::class.java!!.getName()).log(java.util.logging.Level.SEVERE, null, ex)
            }

            // </editor-fold>

            // Create and display the form
            java.awt.EventQueue.invokeLater({ NewSwingTerminalTest().setVisible(true) })
        }
    }
    // End of variables declaration//GEN-END:variables
}
