/*
 * This file is part of lanterna (https://github.com/mabe02/lanterna).
 *
 * lanterna is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright (C) 2010-2024 Martin Berglund
 */
package com.googlecode.lanterna.terminal

import com.googlecode.lanterna.*

import com.googlecode.lanterna.TerminalSize
import com.googlecode.lanterna.terminal.swing.ScrollingAWTTerminal
import com.googlecode.lanterna.terminal.swing.TerminalEmulatorColorConfiguration
import com.googlecode.lanterna.terminal.swing.TerminalEmulatorDeviceConfiguration
import com.googlecode.lanterna.terminal.swing.SwingTerminalFontConfiguration
import java.awt.BorderLayout
import java.util.Random
import javax.swing.*

/**
 * 
 * @author Martin
 */
@SuppressWarnings("FieldCanBeLocal")
 class ScrollingAWTTerminalTest:javax.swing.JFrame() {
private val scrollingAwtTerminal:ScrollingAWTTerminal?

 // Variables declaration - do not modify//GEN-BEGIN:variables
    private var buttonMoveCursor:javax.swing.JButton? = null
private var buttonPrint100Lines:javax.swing.JButton? = null
private var buttonPrint10Lines:javax.swing.JButton? = null
private var buttonPrint1Line:javax.swing.JButton? = null
private var jSeparator1:javax.swing.JSeparator? = null
private var panelTerminalContainer:javax.swing.JPanel? = null
/**
 * Creates new form ScrollingSwingTerminalTest
 */
    init{
initComponents()
scrollingAwtTerminal = ScrollingAWTTerminal(
TerminalEmulatorDeviceConfiguration.getDefault().withLineBufferScrollbackSize(150), 
SwingTerminalFontConfiguration.getDefault(), 
TerminalEmulatorColorConfiguration.getDefault())
panelTerminalContainer!!.add(scrollingAwtTerminal, BorderLayout.CENTER)
pack()
}

/**
 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
 * content of this method is always regenerated by the Form Editor.
 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private fun initComponents() {

panelTerminalContainer = javax.swing.JPanel()
buttonPrint100Lines = javax.swing.JButton()
jSeparator1 = javax.swing.JSeparator()
buttonPrint10Lines = javax.swing.JButton()
buttonPrint1Line = javax.swing.JButton()
buttonMoveCursor = javax.swing.JButton()

setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE)

panelTerminalContainer!!.setBorder(javax.swing.BorderFactory.createTitledBorder("Terminal"))
panelTerminalContainer!!.setLayout(java.awt.BorderLayout())

buttonPrint100Lines!!.setText("Print 100 lines")
buttonPrint100Lines!!.addActionListener(Runnable({ this.buttonPrint100LinesActionPerformed(it) }))

buttonPrint10Lines!!.setText("Print 10 lines")
buttonPrint10Lines!!.addActionListener(Runnable({ this.buttonPrint10LinesActionPerformed(it) }))

buttonPrint1Line!!.setText("Print 1 line")
buttonPrint1Line!!.addActionListener(Runnable({ this.buttonPrint1LineActionPerformed(it) }))

buttonMoveCursor!!.setText("Move cursor")
buttonMoveCursor!!.addActionListener(Runnable({ this.buttonMoveCursorActionPerformed(it) }))

val layout = javax.swing.GroupLayout(getContentPane())
getContentPane().setLayout(layout)
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addContainerGap()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(panelTerminalContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
.addGap(6, 6, 6)
.addComponent(buttonMoveCursor)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
.addComponent(buttonPrint1Line)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(buttonPrint10Lines)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(buttonPrint100Lines))
.addComponent(jSeparator1))
.addContainerGap())
)
layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addContainerGap()
.addComponent(panelTerminalContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
.addGap(18, 18, 18)
.addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(buttonPrint100Lines)
.addComponent(buttonPrint10Lines)
.addComponent(buttonPrint1Line)
.addComponent(buttonMoveCursor))
.addContainerGap())
)

pack()
}// </editor-fold>//GEN-END:initComponents

private fun buttonPrint100LinesActionPerformed(evt:java.awt.event.ActionEvent?) {//GEN-FIRST:event_buttonPrint100LinesActionPerformed
printLines(100)
}//GEN-LAST:event_buttonPrint100LinesActionPerformed

private fun buttonPrint10LinesActionPerformed(evt:java.awt.event.ActionEvent?) {//GEN-FIRST:event_buttonPrint10LinesActionPerformed
printLines(10)
}//GEN-LAST:event_buttonPrint10LinesActionPerformed

private fun buttonPrint1LineActionPerformed(evt:java.awt.event.ActionEvent?) {//GEN-FIRST:event_buttonPrint1LineActionPerformed
printLines(1)
}//GEN-LAST:event_buttonPrint1LineActionPerformed

private fun buttonMoveCursorActionPerformed(evt:java.awt.event.ActionEvent?) {//GEN-FIRST:event_buttonMoveCursorActionPerformed
val terminalSize = scrollingAwtTerminal!!.getTerminalSize()
val random = Random()
scrollingAwtTerminal!!.setCursorPosition(random.nextInt(terminalSize!!.getColumns()), random.nextInt(terminalSize!!.getRows()))
scrollingAwtTerminal!!.flush()
}//GEN-LAST:event_buttonMoveCursorActionPerformed

private fun printLines(howMany:Int) {
val random = Random()
val selection = "abcdefghijklmnopqrstuvxyzåäö"
for (i in 0 until howMany)
{
val words = random.nextInt(10) + 1
for (j in 0 until words)
{
val length = random.nextInt(10) + 2
for (k in 0 until length)
{
scrollingAwtTerminal!!.putCharacter(selection.charAt(random.nextInt(selection.length)))
}
scrollingAwtTerminal!!.putCharacter(' ')
}
scrollingAwtTerminal!!.putCharacter('\n')
}
scrollingAwtTerminal!!.flush()
}

companion object {

private val serialVersionUID = 1L

/**
 * @param args the command line arguments
 */
     fun main(args:Array<String?>?) {
 /* Set the Nimbus look and feel */
        try
{
UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName())
}
catch (ex:ClassNotFoundException) {
java.util.logging.Logger.getLogger(ScrollingAWTTerminalTest::class.java!!.getName()).log(java.util.logging.Level.SEVERE, null, ex)
}
catch (ex:InstantiationException) {
java.util.logging.Logger.getLogger(ScrollingAWTTerminalTest::class.java!!.getName()).log(java.util.logging.Level.SEVERE, null, ex)
}
catch (ex:UnsupportedLookAndFeelException) {
java.util.logging.Logger.getLogger(ScrollingAWTTerminalTest::class.java!!.getName()).log(java.util.logging.Level.SEVERE, null, ex)
}
catch (ex:IllegalAccessException) {
java.util.logging.Logger.getLogger(ScrollingAWTTerminalTest::class.java!!.getName()).log(java.util.logging.Level.SEVERE, null, ex)
}

 /* Create and display the form */
        java.awt.EventQueue.invokeLater({ ScrollingAWTTerminalTest().setVisible(true) })
}
}
 // End of variables declaration//GEN-END:variables
}
