kotlin.code.style=official
kotlin.native.ignoreDisabledTargets=true
kotlin.native.enableKlibsCrossCompilation=true
kotlin.mpp.applyDefaultHierarchyTemplate=false

GROUP=com.github.La-Manufacture-Ambulante.codex24-lanterna-kmp2
VERSION_NAME=dev-SNAPSHOT
POM_NAME=Lanterna KMP Core
POM_DESCRIPTION=Kotlin Multiplatform migration of Lanterna core APIs.
POM_URL=https://github.com/La-Manufacture-Ambulante/codex24-lanterna-kmp2
POM_SCM_URL=https://github.com/La-Manufacture-Ambulante/codex24-lanterna-kmp2
POM_SCM_CONNECTION=scm:git:https://github.com/La-Manufacture-Ambulante/codex24-lanterna-kmp2.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/La-Manufacture-Ambulante/codex24-lanterna-kmp2.git
POM_LICENSE_NAME=Apache License 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_DEVELOPER_ID=la-manufacture-ambulante
POM_DEVELOPER_NAME=La Manufacture Ambulante
